[package]
name = "my-aoc2024-solutions"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Relacibo/my-aoc2024-solutions"

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.94"
memoize = "0.4.2"
rayon = "1.10.0"
regex = "1.11.1"
